version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: market
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"